const QUERY_ALIASES: Record<string, string> = {

  // ─── MERN / Full Stack ───────────────────────────────────────
  "mern":                        "mern stack developer",
  "mern stack":                  "mern stack developer",
  "mern developer":              "mern stack developer",
  "fullstack":                   "full stack developer",
  "full stack":                  "full stack developer",
  "full-stack":                  "full stack developer",
  "full stack developer":        "full stack developer",

  // ─── Frontend ────────────────────────────────────────────────
  "frontend":                    "frontend developer",
  "front end":                   "frontend developer",
  "front-end":                   "frontend developer",
  "react":                       "react developer",
  "reactjs":                     "react developer",
  "react.js":                    "react developer",
  "react developer":             "react developer",
  "vue":                         "vue.js developer",
  "vuejs":                       "vue.js developer",
  "vue.js":                      "vue.js developer",
  "angular":                     "angular developer",
  "angularjs":                   "angular developer",
  "next":                        "next.js developer",
  "nextjs":                      "next.js developer",
  "next.js":                     "next.js developer",
  "ui developer":                "frontend developer",
  "ui/ux developer":             "frontend developer",

  // ─── Backend ─────────────────────────────────────────────────
  "backend":                     "backend developer",
  "back end":                    "backend developer",
  "back-end":                    "backend developer",
  "node":                        "node.js developer",
  "nodejs":                      "node.js developer",
  "node.js":                     "node.js developer",
  "node developer":              "node.js developer",
  "python":                      "python developer",
  "python developer":            "python developer",
  "django":                      "django developer",
  "flask":                       "flask developer",
  "java":                        "java developer",
  "java developer":              "java developer",
  "spring":                      "spring boot developer",
  "spring boot":                 "spring boot developer",
  "php":                         "php developer",
  "laravel":                     "laravel developer",
  "golang":                      "golang developer",
  "go developer":                "golang developer",
  "ruby":                        "ruby on rails developer",
  "rails":                       "ruby on rails developer",
  "ruby on rails":               "ruby on rails developer",
  "dotnet":                      ".net developer",
  ".net":                        ".net developer",
  "c#":                          ".net developer",
  "asp.net":                     ".net developer",

  // ─── Mobile ──────────────────────────────────────────────────
  "android":                     "android developer",
  "android developer":           "android developer",
  "ios":                         "ios developer",
  "ios developer":               "ios developer",
  "swift":                       "ios developer",
  "kotlin":                      "android developer",
  "flutter":                     "flutter developer",
  "react native":                "react native developer",
  "mobile developer":            "mobile app developer",
  "mobile":                      "mobile app developer",

  // ─── Cloud & DevOps ──────────────────────────────────────────
  "devops":                      "devops engineer",
  "dev ops":                     "devops engineer",
  "aws":                         "aws cloud engineer",
  "aws engineer":                "aws cloud engineer",
  "aws developer":               "aws cloud engineer",
  "amazon web services":         "aws cloud engineer",
  "azure":                       "azure cloud engineer",
  "microsoft azure":             "azure cloud engineer",
  "gcp":                         "google cloud engineer",
  "google cloud":                "google cloud engineer",
  "cloud":                       "cloud engineer",
  "cloud engineer":              "cloud engineer",
  "kubernetes":                  "kubernetes engineer",
  "k8s":                         "kubernetes engineer",
  "docker":                      "devops engineer",
  "terraform":                   "devops engineer",
  "ci/cd":                       "devops engineer",
  "site reliability":            "site reliability engineer",
  "sre":                         "site reliability engineer",

  // ─── Data & Analytics ────────────────────────────────────────
  "data analyst":                "data analyst",
  "data analysis":               "data analyst",
  "data analytics":              "data analyst",
  "business analyst":            "business analyst",
  "ba":                          "business analyst",
  "data scientist":              "data scientist",
  "data science":                "data scientist",
  "data engineer":               "data engineer",
  "data engineering":            "data engineer",
  "big data":                    "data engineer",
  "etl":                         "data engineer",
  "sql":                         "database developer",
  "database":                    "database administrator",
  "dba":                         "database administrator",
  "tableau":                     "data analyst",
  "power bi":                    "data analyst",
  "excel analyst":               "data analyst",

  // ─── AI & Machine Learning ───────────────────────────────────
  "ai":                          "ai engineer",
  "artificial intelligence":     "ai engineer",
  "ml":                          "machine learning engineer",
  "machine learning":            "machine learning engineer",
  "deep learning":               "machine learning engineer",
  "nlp":                         "nlp engineer",
  "computer vision":             "computer vision engineer",
  "llm":                         "ai engineer",
  "generative ai":               "ai engineer",
  "prompt engineer":             "ai engineer",

  // ─── Cybersecurity ───────────────────────────────────────────
  "cybersecurity":               "cybersecurity analyst",
  "cyber security":              "cybersecurity analyst",
  "security analyst":            "cybersecurity analyst",
  "ethical hacker":              "ethical hacker",
  "penetration tester":          "penetration tester",
  "pen tester":                  "penetration tester",
  "pentest":                     "penetration tester",
  "soc analyst":                 "soc analyst",
  "information security":        "cybersecurity analyst",
  "infosec":                     "cybersecurity analyst",
  "network security":            "network security engineer",

  // ─── QA & Testing ────────────────────────────────────────────
  "qa":                          "qa engineer",
  "quality assurance":           "qa engineer",
  "qa engineer":                 "qa engineer",
  "qa analyst":                  "qa engineer",
  "test engineer":               "qa engineer",
  "automation testing":          "automation test engineer",
  "selenium":                    "automation test engineer",
  "manual testing":              "qa engineer",

  // ─── Design & UX ─────────────────────────────────────────────
  "ui ux":                       "ui ux designer",
  "ui/ux":                       "ui ux designer",
  "ux designer":                 "ui ux designer",
  "ui designer":                 "ui ux designer",
  "graphic designer":            "graphic designer",
  "graphic design":              "graphic designer",
  "product designer":            "product designer",
  "figma designer":              "ui ux designer",
  "motion designer":             "motion graphics designer",
  "motion graphics":             "motion graphics designer",
  "visual designer":             "visual designer",

  // ─── Product & Project Management ────────────────────────────
  "product manager":             "product manager",
  "pm":                          "product manager",
  "product management":          "product manager",
  "project manager":             "project manager",
  "project management":          "project manager",
  "scrum master":                "scrum master",
  "agile":                       "agile project manager",
  "program manager":             "program manager",
  "delivery manager":            "delivery manager",

  // ─── Finance & Accounting ────────────────────────────────────
  "finance":                     "finance analyst",
  "financial analyst":           "finance analyst",
  "ca":                          "chartered accountant",
  "chartered accountant":        "chartered accountant",
  "accountant":                  "accountant",
  "accounting":                  "accountant",
  "cpa":                         "certified public accountant",
  "tax":                         "tax consultant",
  "tax analyst":                 "tax consultant",
  "tax consultant":              "tax consultant",
  "audit":                       "auditor",
  "auditor":                     "auditor",
  "investment banking":          "investment banking analyst",
  "investment banker":           "investment banking analyst",
  "equity research":             "equity research analyst",
  "financial planning":          "financial planning analyst",
  "fp&a":                        "financial planning analyst",
  "banking":                     "banking professional",
  "credit analyst":              "credit analyst",
  "risk analyst":                "risk analyst",
  "risk management":             "risk analyst",
  "treasury":                    "treasury analyst",
  "payroll":                     "payroll specialist",

  // ─── Marketing ───────────────────────────────────────────────
  "marketing":                   "marketing manager",
  "digital marketing":           "digital marketing manager",
  "seo":                         "seo specialist",
  "seo specialist":              "seo specialist",
  "sem":                         "sem specialist",
  "ppc":                         "ppc specialist",
  "google ads":                  "ppc specialist",
  "social media":                "social media manager",
  "social media marketing":      "social media manager",
  "content writer":              "content writer",
  "content writing":             "content writer",
  "copywriter":                  "copywriter",
  "copywriting":                 "copywriter",
  "brand manager":               "brand manager",
  "performance marketing":       "performance marketing manager",
  "growth hacker":               "growth marketing manager",
  "growth marketing":            "growth marketing manager",
  "email marketing":             "email marketing specialist",
  "influencer marketing":        "influencer marketing manager",
  "marketing analyst":           "marketing analyst",

  // ─── Sales ───────────────────────────────────────────────────
  "sales":                       "sales executive",
  "sales executive":             "sales executive",
  "sales manager":               "sales manager",
  "business development":        "business development manager",
  "bdm":                         "business development manager",
  "bde":                         "business development executive",
  "account manager":             "account manager",
  "account executive":           "account executive",
  "inside sales":                "inside sales executive",
  "field sales":                 "field sales executive",
  "b2b sales":                   "b2b sales executive",
  "b2c sales":                   "b2c sales executive",
  "pre sales":                   "pre sales consultant",
  "crm":                         "crm executive",

  // ─── Human Resources ─────────────────────────────────────────
  "hr":                          "hr manager",
  "human resources":             "hr manager",
  "hr manager":                  "hr manager",
  "hr executive":                "hr executive",
  "recruiter":                   "recruiter",
  "talent acquisition":          "talent acquisition specialist",
  "recruitment":                 "recruiter",
  "hrbp":                        "hr business partner",
  "hr business partner":         "hr business partner",
  "payroll hr":                  "payroll specialist",
  "learning and development":    "learning and development manager",
  "l&d":                         "learning and development manager",
  "training":                    "training manager",

  // ─── Customer Support & Call Center ──────────────────────────
  "customer support":            "customer support executive",
  "customer service":            "customer service executive",
  "call center":                 "call center executive",
  "bpo":                         "bpo executive",
  "voice process":               "call center executive",
  "non voice":                   "back office executive",
  "chat support":                "customer support executive",
  "technical support":           "technical support engineer",
  "tech support":                "technical support engineer",
  "helpdesk":                    "it helpdesk support",
  "help desk":                   "it helpdesk support",
  "customer success":            "customer success manager",

  // ─── Data Entry & Back Office ────────────────────────────────
  "data entry":                  "data entry operator",
  "data entry operator":         "data entry operator",
  "back office":                 "back office executive",
  "back-office":                 "back office executive",
  "data processing":             "data entry operator",
  "data management":             "data management analyst",
  "ms office":                   "data entry operator",
  "mis":                         "mis executive",
  "mis executive":               "mis executive",
  "mis analyst":                 "mis executive",
  "operations executive":        "operations executive",
  "operations":                  "operations executive",

  // ─── Consulting ──────────────────────────────────────────────
  "consulting":                  "management consultant",
  "consultant":                  "management consultant",
  "management consulting":       "management consultant",
  "strategy consultant":         "strategy consultant",
  "it consultant":               "it consultant",
  "erp consultant":              "erp consultant",
  "sap":                         "sap consultant",
  "sap consultant":              "sap consultant",
  "salesforce":                  "salesforce consultant",
  "salesforce developer":        "salesforce developer",
  "oracle":                      "oracle consultant",

  // ─── Healthcare ──────────────────────────────────────────────
  "doctor":                      "medical officer",
  "physician":                   "medical officer",
  "nurse":                       "registered nurse",
  "nursing":                     "registered nurse",
  "pharmacist":                  "pharmacist",
  "medical":                     "medical officer",
  "healthcare":                  "healthcare professional",
  "clinical":                    "clinical researcher",
  "lab technician":              "lab technician",
  "radiologist":                 "radiologist",
  "physiotherapist":             "physiotherapist",

  // ─── Legal ───────────────────────────────────────────────────
  "lawyer":                      "lawyer",
  "advocate":                    "advocate",
  "legal":                       "legal professional",
  "legal counsel":               "legal counsel",
  "compliance":                  "compliance officer",
  "paralegal":                   "paralegal",
  "legal advisor":               "legal advisor",

  // ─── Education & Teaching ────────────────────────────────────
  "teacher":                     "teacher",
  "teaching":                    "teacher",
  "professor":                   "professor",
  "lecturer":                    "lecturer",
  "tutor":                       "tutor",
  "trainer":                     "corporate trainer",
  "faculty":                     "faculty",
  "education":                   "education professional",
  "academic":                    "academic professional",
  "edtech":                      "edtech professional",

  // ─── Logistics & Supply Chain ────────────────────────────────
  "logistics":                   "logistics manager",
  "supply chain":                "supply chain manager",
  "warehouse":                   "warehouse manager",
  "procurement":                 "procurement manager",
  "inventory":                   "inventory manager",
  "scm":                         "supply chain manager",
  "import export":               "import export executive",
  "freight":                     "freight coordinator",

  // ─── Architecture & Civil ────────────────────────────────────
  "architect":                   "architect",
  "civil engineer":              "civil engineer",
  "civil":                       "civil engineer",
  "structural engineer":         "structural engineer",
  "interior designer":           "interior designer",
  "autocad":                     "autocad designer",
  "site engineer":               "site engineer",

  // ─── Mechanical & Electrical ─────────────────────────────────
  "mechanical engineer":         "mechanical engineer",
  "mechanical":                  "mechanical engineer",
  "electrical engineer":         "electrical engineer",
  "electrical":                  "electrical engineer",
  "electronics":                 "electronics engineer",
  "embedded":                    "embedded systems engineer",
  "iot":                         "iot engineer",
  "robotics":                    "robotics engineer",
  "automation engineer":         "automation engineer",
  "plc":                         "plc programmer",

  // ─── Real Estate ─────────────────────────────────────────────
  "real estate":                 "real estate agent",
  "property":                    "property consultant",
  "real estate agent":           "real estate agent",
  "property manager":            "property manager",

  // ─── Media & Journalism ──────────────────────────────────────
  "journalist":                  "journalist",
  "reporter":                    "journalist",
  "editor":                      "editor",
  "video editor":                "video editor",
  "video editing":               "video editor",
  "photographer":                "photographer",
  "videographer":                "videographer",
  "content creator":             "content creator",
  "anchor":                      "news anchor",

  // ─── Internships ─────────────────────────────────────────────
  "internship":                  "internship",
  "intern":                      "internship",
  "fresher":                     "fresher jobs",
  "fresher jobs":                "fresher jobs",
  "entry level":                 "entry level jobs",
  "graduate trainee":            "graduate trainee",
  "management trainee":          "management trainee",
};

export function normalizeSearchQuery(q: string): string {
  const cleaned = q.toLowerCase().trim().replace(/\s+/g, " ");
  return QUERY_ALIASES[cleaned] ?? cleaned;
}